# Mandatory
server:
  port: 5002

# Mandatory.
cache:
  host: "redis"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 1

# Optional.
responseCache:
  # mongoURL: "mongodb://root:test@mongodb:27017/ps?authSource=admin"
  mongoURL: "mongodb://mongodb:27017/ps?authSource=admin"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  synchronous: 
    # mongoURL: "mongodb://root:test@mongodb:27017/ps?authSource=admin"
    mongoURL: "mongodb://mongodb:27017/ps?authSource=admin"

# Mandatory.
app:
  # Mandatory.
  mode: bap

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: network
    inboxQueue: "inbox"
    outboxQueue: "outbox"
    amqpURL: "amqp://guest:guest@rabbitmq:5672"

  # Mandatory.
  actions:
    requests:
      search:
        ttl : "PT20S"
      init:
        ttl : "PT10S"
      select:
        ttl : "PT10S"
      confirm:
        ttl : "PT10S"
      status:
        ttl : "PT10S"
      get_cancellation_reasons:
        ttl: "PT10S"
      get_rating_categories:
        ttl: "PT10S"
    
    responses: 
      on_search:
        ttl: "PT20S"
      
      on_init:
        ttl: "PT10S"
      on_select:
        ttl: "PT10S"
      on_confirm:
        ttl: "PT10S"
      on_status:
        ttl: "PT10S"
      cancellation_reasons:
        ttl: "PT10S"
      rating_categories:
        ttl: "PT10S"
  
  # Mandatory.
  privateKey: "bIAu+fgRqyJn1FCcEr8K++EGXyH2TGxxF+cMq2ynikzazsmH1RdLdL764E2RL+0d+r1cT3vjLRLBwE2qxCOCjw=="
  publicKey: "2s7Jh9UXS3S++uBNkS/tHfq9XE974y0SwcBNqsQjgo8="

  # Mandatory.
  subscriberId: "aloy-test-bap-network"
  subscriberUri: "https://aloy-bap-network.loca.lt/"
  
  # Mandatory.
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: false
  uniqueKey: "aloy_bap_network_key"
  
  # Mandatory.
  city: "std:080"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 2
  telemetry:
    enabled: false
    url: ""
    batchSize: 100
    # In minutes
    syncInterval: 30
    redis_db: 3
